field_name: organigrams_border_color_hover
type: textfield
label: 'Border color hover'
description: 'Specify the border color of the items in this organigram on hover if they have a URL.'
field_group: 'Item settings'
field_group_weight: 2
weight: 9
