field_name: organigrams_background_color_hover
type: textfield
label: 'Background color hover'
description: 'Specify the background color of the items in this organigram on hover if they have a URL.'
field_group: 'Item settings'
field_group_weight: 2
weight: 11
