field_name: organigrams_bottom_radius
type: textfield
label: 'Bottom radius'
default: 0
description: 'Specify the radius of the bottom corners in pixels of the items in this organigram.'
field_group: 'Item settings'
field_group_weight: 2
weight: 4
