field_name: organigrams_horizontal_space
type: textfield
label: 'Horizontal space'
default: 20
description: 'Specify the horizontal space in pixels between the items in this organigram.'
field_group: 'Item settings'
field_group_weight: 2
weight: 6
