field_name: organigrams_node_height
type: textfield
label: 'Item height'
default: 30
description: 'Specify the height in pixels of the items in this organigram.'
field_group: 'Item settings'
field_group_weight: 2
weight: 2
