field_name: organigrams_shadow_offset
type: textfield
label: 'Shadow offset'
default: 0
description: 'Specify the shadow offset in pixels of the items in this organigram.'
field_group: 'Item settings'
field_group_weight: 2
weight: 5
