media.type.*.third_party.media_entity_file_redirect:
  type: mapping
  label: 'Media entity file redirect settings'
  mapping:
    enabled:
      type: boolean
      label: 'Redirect canonical path to file source'
