field_name: field_o_font_color
label: 'Font color'
description: 'Specify the font color of this organigram item.'
required: false
translatable: false
default_value: {  }
widget_type: text_textfield
weight: 18
