field_name: field_o_background_color
label: 'Background color'
description: 'Specify the background color of this organigram item.'
required: false
translatable: false
default_value: {  }
widget_type: text_textfield
weight: 13
