field_name: field_o_border_color_hover
label: 'Border color hover'
description: 'Specify the border color of this organigram item when hovering over it if it has a URL.'
required: false
translatable: false
default_value: {  }
widget_type: text_textfield
weight: 16
